[[plugins]]
  package = "@netlify/plugin-lighthouse"
   [plugins.inputs.settings]
    preset = "desktop"
    locale = "fr"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
